
name: Manual Build for MIPS Soft-Float

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 绕过镜像损坏的默认版本，指定安装 2026-08-01 的纯净版 Nightly
      - name: Build with rust-musl-cross (Soft-Float)
        run: |
          docker run --rm \
            -e CARGO_PROFILE_RELEASE_LTO="false" \
            -e RUSTFLAGS="-C target-feature=+soft-float" \
            -v ${{ github.workspace }}:/home/rust/src \
            messense/rust-musl-cross:mipsel-musl \
            bash -c "rustup toolchain install nightly-2026-08-01 --profile minimal && \
                     rustup component add rust-src --toolchain nightly-2026-08-01 && \
                     cargo +nightly-2026-08-01 build --release -Z build-std=std,panic_abort --target mipsel-unknown-linux-musl"
          sudo chown -R $USER:$USER target/
      # 提取并上传编译结果
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarkdrive-webdav-mips-softfloat
          path: target/mipsel-unknown-linux-musl/release/quarkdrive-webdav
