name: Manual Build for MIPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 直接使用专门为 MIPS musl 打包的 Docker 镜像进行跨平台编译
      - name: Build with rust-musl-cross
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/rust/src messense/rust-musl-cross:mipsel-musl cargo build --release
          sudo chown -R $USER:$USER target/

      # 提取并上传编译好的二进制文件
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarkdrive-webdav-mips
          path: target/mipsel-unknown-linux-musl/release/quarkdrive-webdav
